### ISSUE TITLE
Mobile - Header: Search should be collapsed and only the icon should be visible

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#110]
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/282815784)

## Expected Behaviour
The search input field shouldn't appear on mobile until you tap on the search icon (magnifying glass).

## Note
All icons are from [Material Icons](material.io/icons/)

## Work Needed
- [ ] Works on mobile
- [ ] Works on desktop
- [ ] Wrote some tests

**Comment by s-kennedy** [comment]
For now I just removed the search field in the navbar.

@heymosef What happens when the user clicks on the search icon? Where does the search field go? There's not enough room in the navbar without covering the logo.
