### ISSUE TITLE
Mobile - Header: Logo should be larger (and legible)

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#112]
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/282815784)

## Expected Behaviour
Please view the designs for how the logo appears (height: 16px)

## Work Needed
- [ ] Works on mobile
- [ ] Works on desktop
- [ ] Wrote some tests

**Comment by s-kennedy** [comment]
Closed in #128
