### ISSUE TITLE
Mobile - Filter Results: Hide all the filter options (city and filter) in the sidebar inside a dropdown

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#114]
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/282815784)

## Expected Behaviour
The filter option sidebar should be grouped inside a dropdown that sticks to the top of the screen as you scroll down. When you tap on the "Filter results" bar it should take over the full screen (per design) for the user to make their selections.

## Work Needed
- [ ] Works on mobile
- [ ] Works on desktop
- [ ] Wrote some tests

**Comment by dragonza** [comment]
Hey @heymosef , As I checked, the button is hidden on mobile

**Comment by heymosef** [comment]
@dragonza Is this currently on beta.womenandcolor.com? To clarify, this is for the filter options and not the top navigation.
