### ISSUE TITLE
Speaker should be directed to Edit Profile after going through onboarding

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#165]
## Description
Currently, when a person signs up as a speaker, they are redirected to the homepage after entering their details in the onboarding screens (last one being Social). The speaker should be directed to the Edit Profile screen after the Social screen; not the home page.

## Work Needed
- [ ] Works on mobile
- [ ] Works on desktop
- [ ] Wrote some tests

**Comment by s-kennedy** [comment]
Fixed in #173
