### ISSUE TITLE
Talks page - UI only

### ISSUE THREAD

**Issue by MattGiesa** [CivicTechTO/women-and-color-frontend#39]
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/265986248)

## Description
Users need a way to add the talks they've done to their profile. The design indicates a Talks page which allows users to add multiple talks, each including a video link, the name of the event and the name of the talk.

This issue covers the UI only - integrating with the backend will be done in another issue.

Potential concerns/open questions:
are we embedding a video or linking to another service that contains the video?
do we need to validate these links?
how do we get a thumbnail of the video?

I did a quick google search and found [this](https://developers.google.com/youtube/v3/docs/thumbnails), I'm not sure if the youtube api is free or paid but if it's free we could use this to get a thumbnail of any videos on youtube.

## Work Needed
- [ ] Works on mobile
- [ ] Works on desktop

**Comment by dragonza** [comment]
I can work on the components for the UI.  I need to clarify a few points.
![image](https://user-images.githubusercontent.com/10185439/39097668-95e0fe6c-4689-11e8-9ef0-a8ef848f4d7d.png)

- Is the text in red clickable? if yes, where does it lead to?
- Could users add another talk while the others box have empty inputs?
- What is the limit of talks users can add?

**Comment by s-kennedy** [comment]
@dragonza Yes that should be a link that goes to the url submitted in the Link field.

**Comment by dragonza** [comment]
@s-kennedy Thanks for your answer. Some following up questions
As for the thumbnail, will we retrieve thumbnail from the video sites inputted by users? If Yes, what if the site has no such support?

**Comment by s-kennedy** [comment]
@dragonza if there's no thumbnail we can just use a placeholder image, like a media icon or something like that.

**Comment by dragonza** [comment]
@s-kennedy Have we had the placeholder image yet?
Here is the things I will work on this task:

- Create a route for talk and the container component.
- Create the talk component. ( all three fields are required).
- Add more talks functionality. (User can only add more talk if the previous talk is filled in)
- Save change and cancel buttons.

All of the above is UI only.  

Please add more if I missing anything.

**Comment by s-kennedy** [comment]
@dragonza @heymosef what do you think about using this icon for the placeholder? https://material.io/icons/#ic_photo_camera

I'll need to work on the API endpoint for this ... I can probably get it done on Wednesday.

**Comment by heymosef** [comment]
@s-kennedy I feel this one makes more sense for a placeholder image:
https://material.io/icons/#ic_photo

Camera to me feels like action you have to take.

**Comment by s-kennedy** [comment]
how about this one? https://material.io/icons/#ic_account_circle

**Comment by heymosef** [comment]
To confirm: is this icon for speaker talks placeholder or for profile photo placeholder?

**Comment by s-kennedy** [comment]
oh right it's for speaker talks, not the profile photo... i got confused :/
so the one you suggested makes morse sense then  - https://material.io/icons/#ic_photo

**Comment by s-kennedy** [comment]
Fixed in #161
