### ISSUE TITLE
Talks page - integrate with backend

### ISSUE THREAD

**Issue by MattGiesa** [CivicTechTO/women-and-color-frontend#40]
Depends on #39 

## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/265986248)

## Description
Post the talks to the server.

Please create an issue in the backend repo for storing this data in the database and link it below

## Work Needed
- [ ] [Link Backend Issue](https://github.com/CivicTechTO/women-and-color-frontend/issues/000)

**Comment by dragonza** [comment]
Has the backend ready for the integration yet? @s-kennedy

**Comment by s-kennedy** [comment]
Fixed in #161
