### ISSUE TITLE
update the Speaker page's Featured Talks section to retrieve real data

### ISSUE THREAD

**Issue by MattGiesa** [CivicTechTO/women-and-color-frontend#41]
Depends on #40 (I mean really this could be done as soon as data is being stored in the database which should be an issue in the backend repo)

## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/245103731)

## Description
Currently the Featured Talks section of the Speaker page is hardcoded to mock data. Once the Talks page (#39) is completed and it stores data (#40) we can retrieve real data from the server on the Speaker page

**Comment by s-kennedy** [comment]
Fixed in #161
