### ISSUE TITLE
update Speaker page to retrieve real location data

### ISSUE THREAD

**Issue by MattGiesa** [CivicTechTO/women-and-color-frontend#42]
## Description
Currently the Speaker page's location is hardcoded to "Toronto, Canada". This should be updated to pull the real location from the server.

The location property on the speaker object is an ID to a location record. When the speaker is retrieved, only the ID is returned. It would be nice to return the fully loaded location object along with the speaker to avoid making an extra request to the server for just the location. This would mean updating backend code, so if this is done please create an issue in the backend repo for tracking that work.

Alternatively we could load all locations and do a lookup on the client.

Backend issue: https://github.com/CivicTechTO/women-and-color-backend/issues/28

**Comment by s-kennedy** [comment]
Estimated hours: 1
