### ISSUE TITLE
Featured Talks carousel on Speaker page

### ISSUE THREAD

**Issue by MattGiesa** [CivicTechTO/women-and-color-frontend#44]
## Design
![image](https://user-images.githubusercontent.com/23535291/36826832-eea3091c-1cdd-11e8-9bd2-ca9b2ddb963e.png)

[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/245103731)

## Description
The design shows a nice carousel of cards in a single row. The current implementation wraps instead. Please update to match the designs. Feel free to pull in a small react carousel package if necessary. Should work on mobile and desktop (is swipe support important? pan/horizontal scroll should at least work)

## Work Needed
- [ ] Works on mobile
- [ ] Works on desktop

**Comment by s-kennedy** [comment]
An option for the carousel: https://github.com/akiran/react-slick

**Comment by s-kennedy** [comment]
Fixed in #161
