### ISSUE TITLE
Remove the horizontal scrollbar from the public-facing website

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#73]
## Expected Behaviour
There should be no horizontal scroll for any of the pages on the site. The columns and containers should adjust to accommodate the browser width, but there shouldn't be any horizontal scrollbars.

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by MattGiesa** [comment]
@heymosef can you tell us what pages you're seeing a scroll bar on now?
