### ISSUE TITLE
Searching for a topic should update the topic in the heading above the speaker list

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#76]
## Steps To Recreate
1. Go to home page
2. Search for a topic from nav bar or banner

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by srhboo** [comment]
I can grab this - should topic in "Speakers in [cities] for [topic]" be demarcated by quotes / font styling / etc? Or good to just be the search query?
