### ISSUE TITLE
Selecting a filter (speaker identity) should update the heading above the speaker list

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#77]
## Steps To Recreate
1. Go to home page
2. Select any of the options under “filter”

**Note:** For example, selecting “Women” should update the heading to Women in <city> for <topic name>

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by srhboo** [comment]
I can get this too - so just to be sure, the change for example below would be:

"Speakers in all cities for all topics" --> filter by identity: Woman --> "Women in all cities for all topics"?
