### ISSUE TITLE
Speaker’s profile should have the following URL structure “.../speaker/speakers-full-name”

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#78]
## Steps To Recreate
1. Go to home page
2. Click on “View Profile” for any of the speakers listed

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by srhboo** [comment]
@heymosef should speaker ID be included with the full name? (possibility of duplicate full names)

**Comment by MattGiesa** [comment]
It would have to be or we'd have to build a whole feature around custom urls (like LinkedIn profiles). Keeping the ID in the url like `.../speakers/123456/matthew-giesa` would be the fastest/easiest solution. The name then would only be presentational - we wouldn't actually use it for anything, but at least a shared link would tell you what you're about to click on.

**Comment by srhboo** [comment]
thanks @MattGiesa - PR up matching your suggestion
