### ISSUE TITLE
Remove the menu option from the top navigation when in desktop mode

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#80]
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6/#/screens/245103730)

## Expected Behaviour
Menu icon should only appear when the browser width is too small to fit all the items in the top navigation bar

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by MattGiesa** [comment]
the menu button seems to have been removed already:
![image](https://user-images.githubusercontent.com/23535291/37572302-6c800da8-2adf-11e8-9d31-97f802f02910.png)
