### ISSUE TITLE
 Change scheme of “<person name>, <company name>” to “<person name> at <company name>” on the home page

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#81]
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6/#/screens/245103730)

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by MattGiesa** [comment]
duplicate of #85 which has more detail
