### ISSUE TITLE
Remove the menu option from the top navigation when in desktop mode

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#84]
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/245103730)

## Expected Behaviour
There's no need for the menu option on desktop as all the buttons in the navigation bar are visible.

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by MattGiesa** [comment]
the menu button seems to have been removed already:
![image](https://user-images.githubusercontent.com/23535291/37572308-7deff42c-2adf-11e8-8832-a9c1f76048e2.png)
