### ISSUE TITLE
 Speaker’s name and photo should be clickable in the list view

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#93]
## Description
On mobile the "View profile" button doesn't appear. Need to make it easier for people to click on obvious touch points (photo, name, button) to view the profile.

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by s-kennedy** [comment]
@heymosef I think we need to update the link styling for the speaker cards:
<img width="670" alt="screen shot 2018-03-27 at 4 04 31 pm" src="https://user-images.githubusercontent.com/10519011/37991991-9877a38a-31d8-11e8-9053-837601602046.png">
